#!/bin/bash

# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-which-directory-it-is-stored-in
THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

DST_DIR=$THIS_DIR/../protobuf_autogen

protoc --proto_path=$THIS_DIR --java_out=$DST_DIR $THIS_DIR/register_user.proto
protoc --proto_path=$THIS_DIR --java_out=$DST_DIR $THIS_DIR/data_record.proto

rm $DST_DIR/*.pyc
touch $DST_DIR/__init__.py
